enableCoreDump            0
sessionTimeout            3600

errorlog /var/log/litespeed/admin-error.log {
  useServer               1
  logLevel                INFO
  rollingSize             10M
}

accesslog /var/log/litespeed/admin-access.log {
  useServer               1
  rollingSize             10M
  keepDays                1
}

accessControl  {
  allow                   ALL
}

extprocessor AdminPHP {
  type                    fcgi
  address                 uds://tmp/admin_lsphp.sock
  maxConns                10
  env                     PHP_LSAPI_CHILDREN=10
  initTimeout             60
  retryTimeout            0
  persistConn             1
  respBuffer              0
  autoStart               1
  path                    /usr/local/lsws/admin/fcgi-bin/admin_php
  backlog                 100
  instances               1
  runOnStartUp            1
  extMaxIdleTime          300
  priority                0
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           1400
  procHardLimit           1500
}

scripthandler  {
  add                     lsapi:AdminPHP php
}

listener adminListener {
  address                 *:7082
  secure                  0
  map                     _AdminVHost *
}

listener adminListener7082 {
  address                 *:7082
  secure                  0
  map                     _AdminVHost *
}